apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpnt
spec:
  replicas: 3
  selector:
    matchLabels:
      ng: web
  template:
    metadata:
      name: pd
      labels:
        ng: web
    spec:
      containers:
        - name: c1
          image: deepakgonsalves63/ckm
          ports:
            - containerPort: 80
      nodeSelector:
        ns: s1
